import "./styles/style.css";
import addTaskMenu from "./handlers/tasks/addTaskMenu.js";
import renderTasks from "./handlers/tasks/renderTasks.js";
import { getAllTasks } from "./handlers/tasks/taskStorage.js";
import setupModalListeners from "./handlers/tasks/editTask.js";
import addProjectMenu from "./handlers/projects/addProjectMenu";
import { renderAllProjects } from "./handlers/projects/renderProjects";
import { handleProjectEditMenu } from "./handlers/projects/handleProjectEvents";
import setupMobileMenu from "./handlers/setupMobileMenuToggle.js";
addTaskMenu();
setupModalListeners();
addProjectMenu();
renderAllProjects();
handleProjectEditMenu();
setupMobileMenu();
let allTask = getAllTasks();
renderTasks(allTask);
const viewAllTasks = document.getElementById("view-all-tasks-btn");
viewAllTasks.addEventListener("click", () => {
  const appHeadTitle = document.getElementById("main-content-title");
  appHeadTitle.innerText = "All Tasks";
  renderTasks(allTask);
});
console.log("Application started.");
